name: shelf_express
description: A starting point for Dart libraries or applications.
version: 1.0.0

environment:
  sdk: ^3.0.0

dependencies:
  crypto: ^3.0.3
  mime: ^1.0.4
  path: ^1.9.0
  shelf: ^1.4.1
  shelf_multipart: ^1.0.0
  shelf_router: ^1.1.4

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
